---
title: "Exploratory"
author: "Bowei Zhang"
date: "2024-02-27"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(echo = TRUE)
Sys.setLanguage(lang = "en")
library(MASS)
library(tidyverse)
library(caret)
library(gtsummary)
library(medicaldata)
library(GGally)
```

# Load Dataset

```{r}
opt_raw = opt

opt_baseline = opt_raw %>%
  rename(
    ended_37_wk = Preg.ended...37.wk
  ) %>%
  # turn space to NA in ended_37_wk
  select(
    # Outcome
    ended_37_wk, GA.at.outcome, Birthweight,
    # Treatment
    Group,
    # Clinics
    Clinic,
    # demographic
    Age, White, Black, Hisp, Education, Prev.preg, 
    # Coexisting medical condition
    Diabetes, Hypertension, Drug.Add, Use.Alc, # eating disorder
    # dental status ?
    ## missing number of natural teeth
    N.qualifying.teeth, BL..BOP, BL.PD.avg
    #
  ) %>%
   mutate(across(where(is.factor), ~na_if(as.character(.), "   ")))

```


```{r}
# Note: The format is good in HTML but odd in pdf
baseline_table = tbl_summary(opt_baseline, by = Group, missing = "no",
                             label = list(
                               ended_37_wk ~ "Whether Ended Before 37 Weeks",
                               GA.at.outcome ~ "Gestational Age at End of Pregnancy (day)",
                               Hisp ~ "Hispanic",
                               Drug.Add ~ "Drug Addiction",
                               Use.Alc ~ "Alcohol Use",
                               N.qualifying.teeth ~ "Number of Qualifying Teeth",
                               BL..BOP ~ "Percent of tooth sites that bled on probing",
                               BL.PD.avg ~ "Whole-mouth average pocket depth (mm)"
                             ))
add_p(baseline_table, pvalue_fun = function(x) style_pvalue(x, digits = 2))
```


```{r}
ggplot(data = opt_baseline) +
  geom_bar(aes(x = ended_37_wk, fill = Group),
          position = 'dodge') +
  scale_fill_manual(values = c('darkblue', 'darkred')) +
  ggtitle("Distribution of Preterm Birth by Treatment Groups") +
  theme_bw()
```

```{r}
opt_outcome = opt_raw %>%
  rename(ended_37_wk = Preg.ended...37.wk,
         ) %>%
  # turn space to NA in ended_37_wk
  select(
    # Outcome
    ended_37_wk, GA.at.outcome, 
    # Secondary Outcome
    Birthweight, Pre.eclamp, Birth.outcome, Apgar1, Apgar5, 
    V5..PD.4, V5..PD.5, #?
    V5..CAL.2, V5..BOP,
    # missing: birth length, admission to ICU, 
    # demographic
    Age, White, Black, Hisp, Education, Prev.preg, 
    # Coexisting medical condition
    Diabetes, Hypertension, Drug.Add, Use.Alc, # eating disorder
    # dental status ?
    ## missing number of natural teeth
    N.qualifying.teeth, BL..BOP, BL.PD.avg
    #
  )%>%
   mutate(across(where(is.factor), ~na_if(as.character(.), "   ")))
```

