---
title: "Preterm - Birth"
subtitle: "Logistic Regression"
author: "R.G. Thomas"
date: "`r format(Sys.time(), '%B %d, %Y')`"
fontsize: 11pt
geometry: "left=3cm,right=5cm,top=2cm,bottom=2cm"
output:
  pdf_document:
    toc: true
    number_sections: true
    highlight: tango
    keep_tex: true 
---    
    

```{r global_options, include=FALSE}
# these are some optional settings that will change how some features look
# you do not need to change them.
knitr::opts_chunk$set(out.width = "50%", out.height="50%", fig.align="center", warning=FALSE, message=FALSE)
```


```{r, echo=FALSE}

library(tidyverse)
library(medicaldata)
library(knitr)
library(kableExtra)

# --- Notes --- 

# Remember this is a Clinical Trial we do not need to backward selection



```

### Data Cleaning 
```{r}

opt_raw = opt

opt_raw$Preg.ended...37.wk <- as.factor(opt_raw$Preg.ended...37.wk)
  

opt_baseline = opt_raw %>%
  rename(
    ended_37_wk = Preg.ended...37.wk
  ) %>%
  # turn space to NA in ended_37_wk
  select(
    # Outcome
    ended_37_wk, GA.at.outcome, 
    # Treatment
    Group,
    # demographic
    Age, White, Black, Hisp, Education, Prev.preg, 
    # Coexisting medical condition
    Diabetes, Hypertension, Drug.Add, Use.Alc, # eating disorder
    # dental status ?
    ## missing number of natural teeth
    N.qualifying.teeth, BL..BOP, BL.PD.avg
    #
  ) %>%
   mutate(across(where(is.factor), ~na_if(as.character(.), "   ")))



# ---
# Below is the data set for analysis

opt_outcome = opt_raw %>%
  rename(ended_37_wk = Preg.ended...37.wk,
         ) %>%
  # turn space to NA in ended_37_wk
  select(
    # Outcome
    ended_37_wk, GA.at.outcome, 
    # Secondary Outcome
    Birthweight, Pre.eclamp, Birth.outcome, Apgar1, Apgar5, 
    V5..PD.4, V5..PD.5, #?
    V5..CAL.2, V5..BOP,
    # missing: birth length, admission to ICU, 
    # demographic
    Age, White, Black, Hisp, Education, Prev.preg, 
    # Coexisting medical condition
    Diabetes, Hypertension, Drug.Add, Use.Alc, # eating disorder
    # dental status ?
    ## missing number of natural teeth
    N.qualifying.teeth, BL..BOP, BL.PD.avg
    #
  )%>%
   mutate(
     ended_37_wk = as.factor(ended_37_wk),
     cat_birthweight = factor(ifelse(Birthweight < 2500, 0, 1), 
                              levels = c(0, 1)),
     across(where(is.factor), ~na_if(as.character(.), "   "))
   )
```


### Logistic Regression

#### Part 1 - Preterm or Not Preterm

#### Model Fitting 
```{r, echo=FALSE}


# --- Fit Base Model ---

# Convert to factor with explicit levels
opt_outcome$ended_37_wk <- factor(opt_outcome$ended_37_wk, levels = c("No", "Yes"))

# Check the levels
table(opt_outcome$ended_37_wk)

# Check the levels
class(opt_outcome$ended_37_wk)
  
model.preterm <- glm(ended_37_wk ~ . - GA.at.outcome, data = opt_outcome, 
          family = binomial, na.action = na.exclude)

summary(m1)

# --- Variable Selection --- 

# Backward Selection AIC? 



```


#### Part 2 - Birthweight 

```{r, echo=FALSE}

opt_outcome$cat_birthweight <- as.factor(opt_outcome$cat_birthweight)

model.birthweight <- glm(cat_birthweight ~ . - ended_37_wk - GA.at.outcome, 
                         data = opt_outcome, family = binomial, 
                         na.action = na.exclude)


```

