---
title: "FMPH 243B - Project 3"
subtitle: "Preterm Birth"
author: "Jomel Meeko Manzano, Bowei Zhang & Katie Banes"
date: "`r Sys.Date()`"
fontsize: 11pt
geometry: "left=3cm,right=3in,top=2cm,bottom=2cm"
lof: yes
lot: yes
output:
  pdf_document:
    toc: true
    number_sections: true
    highlight: tango
    keep_tex: true
header-includes:
   - \rhead{Lab report}
   - \fancyfoot[L]{\currfilename} %put current file in footer
   - \setlength{\headheight}{13.59999pt}
---

\thispagestyle{fancy}

```{r  include=FALSE}
options(
  knitr.kable.NA = "",
  dplyr.summarise.inform = FALSE, dplyr.print_max = 1e9
)
library(pacman)
p_load(kableExtra, janitor, knitr, tidyverse)

opts_chunk$set(
  warning = F, message = F, echo = F, fig.width = 3.2,
  fig.height = 3, results = "asis", dev = "pdf",
  opts_chunk$set(cache.path = "cache/")
)
```


```{r, include=FALSE}

library(tidyverse)
library(medicaldata)
library(knitr)
library(tableone)

# --- Notes about dataset ---
# This data set contains data on 316 men who had undergone radical prostatectomy and received
# transfusion during or within 30 days of the surgical procedure and had available prostate serum
# antigen (PSA) follow-up data. 

# The main exposure of interest was RBC storage duration group. A
# number of demographic, baseline and prognostic factors were also collected. 

# The outcome was
# time to biochemical (PSA) cancer recurrence. The dataset is cleaned and complete. There are no
# outliers or data problems (more details after variable information). 

```


## Load Data
```{r, echo=FALSE}

dt <- blood_storage

```

## Summary Statistics
```{r, echo=FALSE}



```

